xtext/maven-xtext-example

my.mavenized.herolanguage.releng/pom.xml

Signed-off-by: Michael Vorburger <mike@vorburger.ch>

tycho-version 0.23.0 => 0.24.0

---

.project

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

[eclipse/xtext#1183] Change project name in eclipse to ease import.

---

.project

To match documentation.
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

[eclipse/xtext#1183] Rename project from "root" to "parent".

---

.travis.yml
README.md

added travis file

---

my.mavenized.herolanguage.sdk/feature.xml

fixed updatesite #57

---

pom.xml

[#61] fixed theoretical sec. issue with http downloads

[#61] fixed theoretical sec. issue with http downloads

---

example-project-gradle/build.gradle
example-project/pom.xml
pom.xml

update to 2.18

---

.travis.yml
example-project-gradle/build.gradle
example-project-gradle/gradle/wrapper/gradle-wrapper.properties
example-project/pom.xml
my.mavenized.herolanguage/pom.xml
pom.xml

update to Xtext 2.19

---

example-project-gradle/build.gradle

fixed some gradle deprecations

fixed some gradle deprecations

---

pom.xml

updated tycho version

---

example-project-gradle/build.gradle
example-project-gradle/gradle/wrapper/gradle-wrapper.properties
example-project/pom.xml
my.mavenized.herolanguage/pom.xml
pom.xml

Update to Xtext 2.20

---

.travis.yml
example-project-gradle/build.gradle
example-project/pom.xml
my.mavenized.herolanguage/pom.xml
pom.xml

update to Xtext 2.21

---

example-project-gradle/build.gradle
example-project/pom.xml
my.mavenized.herolanguage.tests/META-INF/MANIFEST.MF
my.mavenized.herolanguage/META-INF/MANIFEST.MF
my.mavenized.herolanguage/pom.xml
pom.xml

update to Xtext 2.22

---

.travis.yml
example-project-gradle/build.gradle
example-project/pom.xml
pom.xml

update to Xtext 2.23

---

example-project-gradle/build.gradle
example-project/pom.xml
my.mavenized.herolanguage.tests/META-INF/MANIFEST.MF
my.mavenized.herolanguage/META-INF/MANIFEST.MF
my.mavenized.herolanguage/pom.xml
pom.xml

update to Xtext 2.24

---

example-project-gradle/build.gradle

sunset jcenter

---

example-project-gradle/build.gradle
example-project/pom.xml
my.mavenized.herolanguage/pom.xml
pom.xml

update to Xtext 2.25.0

---

example-project-gradle/build.gradle
my.mavenized.herolanguage/pom.xml

workaround signer problem maven + new version of xtext gradle plugin

workaround signer problem maven + new version of xtext gradle plugin

---

.github/workflows/build.yml
example-project-gradle/build.gradle
example-project/pom.xml
my.mavenized.herolanguage/pom.xml
pom.xml

update to xtext 2.26

---

pom.xml

update to tycho 2.7.3

---

build.sh
example-project/pom.xml
pom.xml

dont generate p2 dependencies into pom

dont generate p2 dependencies into pom

---

example-project-gradle/build.gradle
example-project/pom.xml
pom.xml

update to Xtext 2.28

---

my.mavenized.herolanguage.ide/.project
my.mavenized.herolanguage.ui/.project
targetplatform.target

That's just cosmetic. Sorry, I should have run the project updates in the previous PR

m2e updated project files

---

example-project-gradle/build.gradle
example-project/pom.xml
pom.xml
targetplatform.target

update to Xtext 2.29

---

example-project-gradle/build.gradle
example-project/.classpath
example-project/.settings/org.eclipse.jdt.core.prefs
example-project/pom.xml
my.mavenized.herolanguage.ide/.classpath
my.mavenized.herolanguage.ide/META-INF/MANIFEST.MF
my.mavenized.herolanguage.tests/.classpath
my.mavenized.herolanguage.tests/META-INF/MANIFEST.MF
my.mavenized.herolanguage.ui/.classpath
my.mavenized.herolanguage.ui/META-INF/MANIFEST.MF
my.mavenized.herolanguage/.classpath
my.mavenized.herolanguage/META-INF/MANIFEST.MF
pom.xml
targetplatform.target

update to java 11 and xtext 2.30

update to java 11 and xtext 2.30

---

.github/workflows/build.yml
example-project-gradle/build.gradle
example-project/pom.xml
pom.xml
targetplatform.target

update to Xtext 2.31.0

---

example-project-gradle/build.gradle
example-project/pom.xml
pom.xml
targetplatform.target

update to Xtext 2.32
